disabled_rules:
  - function_parameter_count
  - type_name
  - identifier_name
  - file_length
  - trailing_comma
  - opening_brace
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - closure_parameter_position
  - force_cast
